Ugly Bandit: Mmmm, more treasure to add to our pile!
Large Bandit: Oi you RUNTS, GET THEM!
Bandit: You sniffing round the wrong camp!
Stupid Bandit: You little stinking maggot, you trying to steal from us?
Bandit: Oi lads, we're under attack!
Silly Bandit: Ahaaaa, look what we have here! Some target practice! Get out your weapons you runts!
Scary Bandit: You messing with the wrong clan!
Bandit: We're under attack! Form up!
Clever Bandit: There's a large group of them, call for reinforcements.
Bandit: Incy wincy spider went up the water spout, then came the bandit and smashed its brains out!
Bandit: Another straggler, more treasure for our chests!
Bandit: This one has looked like he's lost his way. We'll help you... FOR YOUR LIFE!
Bandit: You got some shiny armour on, why don't you give it up for us poor bandits?
