Lord Akatan will once more rule the world by the side of our Lord Gorgoth.
KkKkkkkhhhhhhhhh you will fear the rage of the Imps.
We are cousins of our larger counterparts, the Daemons, but we have the same appetite.
Come, I wish to divulge onto some Human meat.
I'm hungry, an Imps appetite is insatiable.
I'm stronger than I look fool, feel my wrath.
Attack them! They insult us with their presence. 
My Lord is stronger than yours and will defeat you.
Our weapons cut deep and our claws deeper.
For the glory of our Lord Akatan and Lord Gorgoth.
We will retake the pieces of the Soul Key and will open the portal once more!
What is your last words Human?
An Adventurer? You will die like the rest.
