Iron Golem: We are the protectors of the mountains.
Iron Golem: You are not welcome here Andalucian.
Iron Golem: You dare fight against the Golems of the Deadpeaks?
Iron Golem: We are the great Golems of Andalucia.
Iron Golem: We used to live in peace with Andalucians until you fools invaded our lands.
Iron Golem: I will have no pleasure in annihilating you.
Iron Golem: You fight well Andalucian.
Iron Golem: Brothers, we are under attack.
Iron Golem: You will feel our calculated wrath.
Iron Golem: We will destroy you and Gorgath.
Iron Golem: You will not defeat me.