Naga Warrior: We have come to reclaim the overworld.
Naga Sage: We have come from the seas to reclaim our right.
Naga: Die you Land-walker!
Naga Warrior: We come from the underwater city of Antalis, and we come with revenge.
Naga: Death to the Land-walkers!
Naga Warrior: Just as we destroyed the old civilisation here, we will destroy you. Andalucia will fall!
Naga: We are coming to Cyrennica! The city will be ours.
Naga Warrior: Do not dare to stand before us, the world will be ours.
Naga: We are masters of our own fate, we shall defeat you and the armies of Gorgoth.
Naga Sage: Leave this realm Land-walker, this is our land.
Naga Sage: We will sweep you with the power of the oceans!
