Skeleton Warrior: Ahhhhhhh.... you've come as an offering for our great lord.
Skeleton Warrior: Fool! Do you think you can resist the might of Maltai?
Skeleton: Our lord will be pleased once we destroy these cretins.
Skeleton: Ignoble fool, do you DARE contest the might of Maltai and its armies?
Skeleton Warrior: The great lord awaits, kill these helpless runts.
Skeleton Warrior: A group of pitiful Andalucians approach, time to send them back to the realm they came from.
Skeleton: The great lord will shower us with bounty once we despose of these.
Skeleton: ARRRRGHHHH! FOR THE GREAT LORD!
Skeleton Warrior: WE WILL USE YOUR BONES AND FLESH AS OFFERINGS TO OUR LORD.
Skeleton Archer: I can smell the fear from your pitiful bones.
Skeleton: I'll enjoy cutting through your flesshhh...
Skeleton: Mmmmmmm... what will you taste like.....
Skeleton Warrior: Freshh meat......