Squish squish squish...
I will follow you everywhere!
I'm meltiiiinnnngggg!
I bring hope wherever I go!
I am edible, want a bite?
Peaceful tidings master!
Every second i'm with you brings me joy!
Jello at your service!
Thou cans't hurt me!
I can seeee!
Protect me master!
Baby Slime on duty!
What a beautiful day it is!
Im suffocating in my own slime!
I wonder where my brother is...
Surprise! It's me!
Am I cute or am I cute?
