'MURICA!
The most courageous act is still to think for yourself. Aloud.
I'd rather die my way than live yours.
Freedom (n.): To ask nothing. To expect nothing. To depend on nothing.
To find yourself, think for yourself.
There is no more independence in politics than there is in jail.
True independence and freedom can only exist in doing what's right.
Let freedom never perish in your hands.
In the truest sense, freedom cannot be bestowed; it must be achieved.
Freedom is nothing but a chance to be better.
Liberty is the breath of life to nations.
I prefer liberty with danger to peace with slavery.
Freedom is the oxygen of the soul.
