Hisss!
ssssssssss........ BOOM! April Fools!
Sss.sss.ss.... Gotcha!
A day without sunshine is like, night.
Better to understand a little than to misunderstand a lot.
I used to have an open mind but my brains kept falling out.
I won't rise to the occasion, but I'll slide over to it.
If at first you don't succeed, destroy all evidence that you tried.
What happens if you get scared half to death twice?
Hug me... please?
One hug, for the poor Creeper.
People have always understood us wrong, we just want a hug.
