Troll: You went in da' wron' forest mah' brudda'.
Troll: This is our forest now, you gonna' be meat for da' spidas'.
Troll: It's dem' homanz' from Cyrenaka, get em!
Troll: They come to steal our treasure! Don't let dem near da chests!.
Troll: ARRRRGHHHHHAA!!
Troll: What you doin' fool?
Troll: Look what I found sneakin' about in the trees.
Troll: For Eagger! Get de' fools.
Troll: I waz' an adventurer once, den I stuck my sword in one of you humanz headz.
Troll: Meat for da' spidas'!
Troll: Ooooh... this one look to be a big group, call da' tribe togetha'.
Troll: You want to see what we did to da' wispz who lived in dis' place?
Troll: Look, in dose' bushaz' dere be an Andalucian. Get em!
