Soldier of Tripoli: Stand and be prepared, you are entering Guild territory!
Soldier of Tripoli: You can not stand against the Tribe of Tripoli! Stand down and leave.
Soldier of Tripoli: We fight as a unit, the Guilds will be united!
Soldier of Tripoli: Our swords cut deep and our armour is strong, we will not be defeated.
Soldier of Tripoli: Form up men! We have an enemy.
Soldier of Tripoli: ARCHERS!
Soldier of Tripoli: It's a large group, prepare the defences!
Soldier of Tripoli: Swords out men, fight for your lives!
Soldier of Tripoli: We are the berbers of the Tribe of Tripoli, we will not be defeated, we will die for our honour.
Soldier of Tripoli: Shed a tear for your lost ones.
