You will be a worthy sacrifice to our Lord.
Burick will disperse of you.
Do not stand between us and our goal fool.
You will die you foolish Andalucian.
We have killed many innocents in the name of our Lord Gorgoth.
The demon Lord will return once more and he will regain his throne.
Cyrennica is ours!
Andalucia will fall!
Die you fool!
How dare you stand before us?
You are brave, but foolish.
Come Acolytes, let us kill these Adventurers.
